// デモ用モックデータ - Supabase不要

export const CLINIC = {
  name: "サンプル整体院",
  description: "神経整体・姿勢矯正の専門院",
  phone: "03-1234-5678",
  email: "info@sample-seitai.jp",
  themeColor: "#2196F3",
};

export const PATIENTS = [
  {
    id: "p1",
    name: "山田 太郎",
    age: 45,
    gender: "男性",
    occupation: "会社員（デスクワーク）",
    chiefComplaint: "右肩の痛み・首のこり",
    medicalHistory: "特になし",
    memo: "長時間PC作業あり。右肩が上がりにくい。",
    examCount: 5,
    lastExamDate: "2026-03-25",
  },
  {
    id: "p2",
    name: "佐藤 花子",
    age: 32,
    gender: "女性",
    occupation: "保育士",
    chiefComplaint: "腰痛・骨盤の歪み",
    medicalHistory: "出産後の骨盤矯正希望",
    memo: "2歳のお子様あり。抱っこで腰に負担。",
    examCount: 3,
    lastExamDate: "2026-03-22",
  },
  {
    id: "p3",
    name: "鈴木 一郎",
    age: 58,
    gender: "男性",
    occupation: "自営業（飲食）",
    chiefComplaint: "左膝の痛み・歩行困難",
    medicalHistory: "高血圧（服薬中）",
    memo: "立ち仕事が多い。階段の昇降に痛みあり。",
    examCount: 8,
    lastExamDate: "2026-03-27",
  },
  {
    id: "p4",
    name: "田中 美咲",
    age: 28,
    gender: "女性",
    occupation: "事務職",
    chiefComplaint: "頭痛・めまい",
    medicalHistory: "片頭痛（10代から）",
    memo: "ストレスが多いとひどくなる。",
    examCount: 2,
    lastExamDate: "2026-03-20",
  },
  {
    id: "p5",
    name: "中村 健太",
    age: 38,
    gender: "男性",
    occupation: "配送業",
    chiefComplaint: "背中の張り・腕のしびれ",
    medicalHistory: "椎間板ヘルニア（5年前）",
    memo: "重い荷物を扱う。最近しびれが再発。",
    examCount: 4,
    lastExamDate: "2026-03-26",
  },
];

export const EXAMS = [
  {
    id: "e1",
    patientId: "p1",
    patientName: "山田 太郎",
    examDate: "2026-03-25",
    visitType: "再診",
    chiefComplaint: "右肩の痛み・首のこり",
    painLevel: 6,
    diagnosis: {
      label: "右側優位の上部交差症候群",
      summary: "右僧帽筋・肩甲挙筋の過緊張により、肩甲骨の挙上と頭部前方変位が見られます。",
      treatmentArea: "右僧帽筋・肩甲挙筋・胸鎖乳突筋",
      weightBalance: "右重心",
      icon: "warning",
    },
    landmarks: {
      standing: { mastoid: 1, scapula: 1, iliac: 0 },
      seated: { mastoid: 1, scapula: 0, iliac: 0 },
    },
    selfcare: [
      "僧帽筋ストレッチ：首を左に倒し、右肩を下げる（20秒×3セット）",
      "胸椎回旋運動：四つ這いで上半身を左右にゆっくり回す（10回×2セット）",
      "顎引き運動：顎を引いて後頭部を壁に押し付ける（10秒×5回）",
    ],
  },
  {
    id: "e2",
    patientId: "p2",
    patientName: "佐藤 花子",
    examDate: "2026-03-22",
    visitType: "再診",
    chiefComplaint: "腰痛・骨盤の歪み",
    painLevel: 5,
    diagnosis: {
      label: "左側優位の骨盤傾斜パターン",
      summary: "左腸骨稜の挙上により、腰椎側弯と左臀筋群の短縮が見られます。",
      treatmentArea: "左腸腰筋・左臀筋群・腰方形筋",
      weightBalance: "左重心",
      icon: "info",
    },
    landmarks: {
      standing: { mastoid: 0, scapula: -1, iliac: -1 },
      seated: { mastoid: 0, scapula: 0, iliac: -1 },
    },
    selfcare: [
      "骨盤ストレッチ：仰向けで膝を抱え、左右にゆっくり倒す（10回）",
      "腸腰筋ストレッチ：片膝立ちで骨盤を前に押す（20秒×3セット）",
      "ドローイン：仰向けでお腹を凹ませてキープ（10秒×10回）",
    ],
  },
  {
    id: "e3",
    patientId: "p3",
    patientName: "鈴木 一郎",
    examDate: "2026-03-27",
    visitType: "経過観察",
    chiefComplaint: "左膝の痛み・歩行困難",
    painLevel: 4,
    diagnosis: {
      label: "左下肢荷重不均衡パターン",
      summary: "左側への過剰荷重により、左膝関節への負担が増大。骨盤の左傾斜が根本原因。",
      treatmentArea: "左大腿四頭筋・左腸脛靭帯・骨盤周囲筋",
      weightBalance: "左重心",
      icon: "success",
    },
    landmarks: {
      standing: { mastoid: 0, scapula: 0, iliac: -1 },
      seated: { mastoid: 0, scapula: 0, iliac: 0 },
    },
    selfcare: [
      "大腿四頭筋ストレッチ：立位で足首を持ち膝を曲げる（20秒×3セット）",
      "ハムストリングストレッチ：椅子に足を乗せて前屈（20秒×3セット）",
      "片脚立ちバランス：目を開けて片脚30秒キープ（左右3回ずつ）",
    ],
  },
  {
    id: "e4",
    patientId: "p1",
    patientName: "山田 太郎",
    examDate: "2026-03-18",
    visitType: "再診",
    chiefComplaint: "右肩の痛み",
    painLevel: 7,
    diagnosis: {
      label: "右側優位の上部交差症候群",
      summary: "前回より改善傾向。右僧帽筋の緊張はまだ残存。",
      treatmentArea: "右僧帽筋・肩甲挙筋",
      weightBalance: "右重心",
      icon: "warning",
    },
    landmarks: {
      standing: { mastoid: 1, scapula: 1, iliac: 1 },
      seated: { mastoid: 1, scapula: 1, iliac: 0 },
    },
    selfcare: [
      "僧帽筋ストレッチ（20秒×3セット）",
      "胸椎回旋運動（10回×2セット）",
    ],
  },
  {
    id: "e5",
    patientId: "p5",
    patientName: "中村 健太",
    examDate: "2026-03-26",
    visitType: "再診",
    chiefComplaint: "背中の張り・腕のしびれ",
    painLevel: 5,
    diagnosis: {
      label: "胸椎後弯増強パターン",
      summary: "胸椎の後弯が強く、肩甲骨の外転位が見られます。頸椎への負荷増大がしびれの原因。",
      treatmentArea: "菱形筋・中部僧帽筋・広背筋",
      weightBalance: "均等",
      icon: "warning",
    },
    landmarks: {
      standing: { mastoid: 0, scapula: 1, iliac: 0 },
      seated: { mastoid: 0, scapula: 1, iliac: 0 },
    },
    selfcare: [
      "菱形筋強化：壁に背中をつけて肩甲骨を寄せる（10秒×10回）",
      "胸椎伸展：バスタオルを丸めて背中に当て仰向け（2分）",
      "腕神経ストレッチ：腕を水平に伸ばし手首を反らす（15秒×3セット）",
    ],
  },
];

export const MONTHLY_TREND = [
  { month: "10月", count: 28 },
  { month: "11月", count: 35 },
  { month: "12月", count: 22 },
  { month: "1月", count: 31 },
  { month: "2月", count: 38 },
  { month: "3月", count: 42 },
];

export const STATS = {
  thisMonthExams: 42,
  lastMonthExams: 38,
  totalPatients: 87,
  thisWeekExams: 12,
  topDiagnoses: [
    { name: "上部交差症候群", count: 15 },
    { name: "骨盤傾斜パターン", count: 11 },
    { name: "胸椎後弯増強", count: 8 },
  ],
};
